"""Add link and last_modified fields to Submission model

Revision ID: 16acd7084dec
Revises: ec48ef7f946a
Create Date: 2025-05-21 12:25:45.486610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16acd7084dec'
down_revision = 'ec48ef7f946a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('link')

    # ### end Alembic commands ###
