"""Add link field to Submission model

Revision ID: b404c947e257
Revises: 16acd7084dec
Create Date: 2025-05-21 12:43:48.784551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b404c947e257'
down_revision = '16acd7084dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
